spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/formkotlin
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true